### ISSUE TITLE
Unexpected node errors when triggering a scan

### ISSUE THREAD

**Issue by KrisBuytaert** [scalefactory/s3audit#6]
When triggering  

s3audit --bucket=my-bucketname   with the aws creds als environment variables set

(node:135) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/s3audit/lib/formatters/console.js:145:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:135) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:135) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

# node --version 
v12.11.0

Installed via npm install .. 

Not sure if I am using it wrong, if this is a version issu .. or somethnig else

**Comment by KrisBuytaert** [comment]
It does look like the last commit https://github.com/scalefactory/s3audit/commit/cd5b236832908a22b17ed2a79dd147f8b750900d 
Actually fixed the issue ..

Thats awesome !
